#!/bin/bash

bspc config window_gap					12
bspc config split_ratio					0.51
bspc config single_monocle				true
bspc config borderless_monocle			false
bspc config gapless_monocle				false

bspc config focus_follows_pointer		true
bspc config pointer_follows_focus		false
bspc config pointer_motion_interval		5
bspc config pointer_modifier			mod4
bspc config pointer_action1				move
bspc config pointer_action2				resize_side
bspc config pointer_action3				resize_corner

# bspc wm --adopt-orphans
bspc rule -a scratch sticky=on state=floating focus=on
