#!/bin/bash

bspwm_dir="$HOME/.config/bspwm"
rofi_command="rofi -dmenu -theme $bspwm_dir/scripts/bspwm/riceSelector.rasi"
read -r current_rice < "$HOME"/.config/bspwm/.rice

# List rices
options=()
index=0
selected_index=0

for dir in "$bspwm_dir"/rices/*/; do
    rice_name=$(basename "$dir")
    options+=("$rice_name")

    # Check if the current rice matches the current iteration rice
    if [[ "$current_rice" == "$rice_name" ]]; then
        selected_index=$index
    fi

    ((index++))
done

selected=$(printf "%s\n" "${options[@]}" | $rofi_command -selected-row "$selected_index")

[[ -n "$selected" ]] || exit 1
echo "$selected" > "${bspwm_dir}/rice"
bspc wm -r

exit 0
